# Generated by Django 6.1 on 2026-08-31 11:37

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('summary', models.TextField(blank=True)),
                ('visa_notes', models.TextField(blank=True)),
                ('hero_image_url', models.URLField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'countries',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('level', models.CharField(choices=[('foundation', 'Foundation'), ('diploma', 'Diploma'), ('bachelor', 'Bachelor'), ('master', 'Master'), ('phd', 'PhD')], max_length=20)),
                ('duration_months', models.PositiveIntegerField(blank=True, null=True)),
                ('tuition_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('intake_months', models.CharField(blank=True, help_text='e.g. Jan, May, Sep', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['university', 'name'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('counsellor', 'Counsellor')], default='counsellor', max_length=20)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('photo_url', models.URLField(blank=True)),
                ('bio', models.TextField(blank=True)),
                ('languages', models.CharField(blank=True, help_text='Comma separated', max_length=200)),
                ('is_public', models.BooleanField(default=True, help_text='Show on the public counsellors page')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intake', models.CharField(blank=True, help_text='e.g. Sep 2026', max_length=60)),
                ('deadline', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('offer_conditional', 'Conditional offer'), ('offer_unconditional', 'Unconditional offer'), ('rejected', 'Rejected by university'), ('visa_filed', 'Visa filed'), ('visa_approved', 'Visa approved'), ('visa_refused', 'Visa refused'), ('enrolled', 'Enrolled'), ('withdrawn', 'Withdrawn')], default='draft', max_length=30)),
                ('commission_expected', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.course')),
            ],
            options={
                'ordering': ['deadline', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExportLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_count', models.PositiveIntegerField()),
                ('filters', models.CharField(blank=True, max_length=300)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150)),
                ('phone', models.CharField(db_index=True, max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('highest_qualification', models.CharField(blank=True, max_length=120)),
                ('completion_year', models.PositiveIntegerField(blank=True, null=True)),
                ('study_gap_years', models.PositiveIntegerField(blank=True, null=True)),
                ('test_type', models.CharField(choices=[('none', 'No test yet'), ('ielts', 'IELTS'), ('pte', 'PTE'), ('toefl', 'TOEFL'), ('topik', 'TOPIK')], default='none', max_length=20)),
                ('test_score', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('test_date', models.DateField(blank=True, null=True)),
                ('budget_note', models.CharField(blank=True, max_length=120)),
                ('target_intake', models.CharField(blank=True, help_text='e.g. Sep 2026', max_length=60)),
                ('visa_history', models.CharField(choices=[('none', 'Never applied'), ('approved', 'Applied and approved'), ('refused', 'Applied and refused')], default='none', max_length=20)),
                ('visa_history_country', models.CharField(blank=True, max_length=80)),
                ('visa_history_date', models.DateField(blank=True, null=True)),
                ('message', models.TextField(blank=True)),
                ('source', models.CharField(blank=True, db_index=True, max_length=60)),
                ('source_detail', models.CharField(blank=True, max_length=200)),
                ('status', models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('counselling', 'Counselling'), ('docs_pending', 'Documents pending'), ('applied', 'Applied'), ('offer', 'Offer received'), ('visa_filed', 'Visa filed'), ('enrolled', 'Enrolled'), ('lost', 'Lost')], db_index=True, default='new', max_length=20)),
                ('last_contacted_at', models.DateTimeField(blank=True, null=True)),
                ('next_follow_up', models.DateField(blank=True, db_index=True, null=True)),
                ('lost_reason', models.CharField(blank=True, max_length=200)),
                ('consent_given', models.BooleanField(default=False)),
                ('consent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to=settings.AUTH_USER_MODEL)),
                ('interested_countries', models.ManyToManyField(blank=True, related_name='leads', to='core.country')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_type', models.CharField(choices=[('passport', 'Passport'), ('transcript', 'Academic transcript'), ('certificate', 'Certificate'), ('test_score', 'Test score report'), ('bank_statement', 'Bank statement'), ('sponsor', 'Sponsor documents'), ('sop', 'Statement of purpose'), ('other', 'Other')], max_length=30)),
                ('file', models.FileField(upload_to='documents/%Y/%m/')),
                ('is_verified', models.BooleanField(default=False)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='core.application')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='core.lead')),
            ],
        ),
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='handovers_made', to=settings.AUTH_USER_MODEL)),
                ('from_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='handovers_given', to=settings.AUTH_USER_MODEL)),
                ('to_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='handovers_received', to=settings.AUTH_USER_MODEL)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='core.lead')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='application',
            name='lead',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='core.lead'),
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('is_call_log', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='core.lead')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TestPrepBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_type', models.CharField(choices=[('ielts', 'IELTS'), ('pte', 'PTE'), ('toefl', 'TOEFL'), ('topik', 'TOPIK'), ('other', 'Other')], max_length=20)),
                ('title', models.CharField(blank=True, max_length=150)),
                ('start_date', models.DateField()),
                ('schedule_note', models.CharField(blank=True, help_text='e.g. Sun–Thu, 7–9 am', max_length=200)),
                ('duration_weeks', models.PositiveIntegerField(blank=True, null=True)),
                ('fee', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('total_seats', models.PositiveIntegerField(default=20)),
                ('seats_taken', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('instructor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['start_date'],
            },
        ),
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('website', models.URLField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('logo_url', models.URLField(blank=True)),
                ('is_partner', models.BooleanField(default=False, help_text='We earn commission here')),
                ('is_active', models.BooleanField(default=True)),
                ('last_verified_on', models.DateField(blank=True, null=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='universities', to='core.country')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Scholarship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('amount_note', models.CharField(blank=True, help_text='e.g. Up to 50% tuition', max_length=200)),
                ('eligibility', models.TextField(blank=True)),
                ('deadline', models.DateField(blank=True, null=True)),
                ('link', models.URLField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scholarships', to='core.country')),
                ('university', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scholarships', to='core.university')),
            ],
            options={
                'ordering': ['deadline', 'name'],
            },
        ),
        migrations.AddField(
            model_name='course',
            name='university',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='core.university'),
        ),
        migrations.AddField(
            model_name='application',
            name='university',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.university'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['status', 'assigned_to'], name='core_lead_status_86f21d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='university',
            unique_together={('country', 'name')},
        ),
    ]
