# Generated by Django 5.0.6 on 2026-09-08 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='must_change_password',
            field=models.BooleanField(default=True, help_text='Force a new password at next sign in'),
        ),
    ]
