# Generated by Django 5.0.6 on 2026-09-25 05:48

import core.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_user_must_change_password'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', core.models.StaffManager()),
            ],
        ),
        migrations.AddField(
            model_name='document',
            name='original_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='lead',
            name='consent_method',
            field=models.CharField(choices=[('form', 'Ticked the box on the website'), ('verbal', 'Agreed verbally to a counsellor'), ('written', 'Signed a form in the office')], default='form', max_length=20),
        ),
        migrations.AddField(
            model_name='lead',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads_added', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='lead',
            name='phone_key',
            field=models.CharField(blank=True, db_index=True, editable=False, max_length=10),
        ),
        migrations.AddField(
            model_name='user',
            name='auto_assign',
            field=models.BooleanField(default=True, help_text='Receive new students from the website automatically'),
        ),
        migrations.AddField(
            model_name='user',
            name='countries',
            field=models.ManyToManyField(blank=True, help_text='Destinations this counsellor handles. New students interested in these countries go to them first.', related_name='specialists', to='core.country'),
        ),
        migrations.AddField(
            model_name='user',
            name='password_changed_at',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(max_length=255, upload_to=core.models.document_path),
        ),
        migrations.CreateModel(
            name='StatusChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_status', models.CharField(blank=True, max_length=20)),
                ('to_status', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_changes', to='core.lead')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
